### ISSUE TITLE
 java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by chengxinping** [joffrey-bion/krossbow#129]
Hello，When I connect to an unauthorised stomp ,my app will crash

![image](https://user-images.githubusercontent.com/18040985/128984207-0df52a30-28ef-4701-a80f-6d5fdf7145c5.png)

**Comment by joffrey-bion** [comment]
Thanks a lot for reporting this.

It looks like the crash is due to an invalid close reason on the websocket frame (the length is above the protocol limit).
In this case, it's probably due to another exception, and when trying to close the connection we just send the exception message as a reason, which is too long.

I'll take a look so we can at least truncate to the limit.

**Comment by chengxinping** [comment]
the hole reason:   ` java.lang.IllegalArgumentException: reason.size() > 123: Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is java.lang.UnsupportedOperationException: 非法订阅`

**Comment by joffrey-bion** [comment]
Also, could you please translate the last part of the message?

**Comment by chengxinping** [comment]
非法订阅  -> illegal subscription

**Comment by chengxinping** [comment]
![image](https://user-images.githubusercontent.com/18040985/128995982-a8b7ec0b-ef90-4cb7-afa1-202991de6b8d.png)

   when connect url has not permission(such as token expird)，it will throw this exception

**Comment by joffrey-bion** [comment]
Thanks a lot for your responses!

By the way, please avoid posting screenshots of stacktraces / code. Just like on StackOverflow, this is not searchable for other users, and it's also completely unreadable for people relying on screen readers (e.g. people with impaired vision). It's also harder to read on mobile.

Also, again, you haven't followed the bug report template, which means I am missing information and I have to annoy you with Q&A 😄 Next time please take the time to fill in the information, it really helps me and it saves time for both of us 😉

**Comment by chengxinping** [comment]
ok，I get it
Thanks for reply

**Comment by joffrey-bion** [comment]
The fix will be released soon in version 2.2.1

**Comment by joffrey-bion** [comment]
2.2.1 was released, please let me know if you still have issues with this

**Comment by chengxinping** [comment]
The new version solves the problem
Thinks!
