### ISSUE TITLE
`StompClient.connect()` might leak the WS connection if cancelled just before STOMP handshake

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/krossbow#163]
`StompClient.connect()` first opens a web socket and then connects at STOMP level.

If this method is cancelled between the 2, the open web socket is never closed.
This cancellation could happen from outside (the user cancels the calling coroutine) or even from inside (due to the internal connection timeout).

The user has no control over the underlying web socket connection, so it's the responsibility of the `StompClient` to close it.

**Comment by Shusek** [comment]
Do you need any help with this?

**Comment by joffrey-bion** [comment]
Thanks but I already fixed it in the branch for version 3.0! It will be coming soon, I just need to take care of a couple more breaking changes before releasing
