### ISSUE TITLE
Upgrade Kotlin coroutines to version 1.6.0

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/krossbow#167]
Pending stable release (currently in RC)

**Comment by Shusek** [comment]
FYI
After update coroutines to 1.6.0-RC but still on 2.7 krossbow I noticed a change in behavior onCompletion when error/close will appear in the stream.
I guess you corrected it in this change:
https://github.com/joffrey-bion/krossbow/commit/80fb4342ddd68c7b2abcb891b5b5b6e86f636672

**Comment by joffrey-bion** [comment]
@Shusek yes I was not sure whether this is due to coroutines 1.6, or the rework of the internals of the STOMP session, but now I have confirmation, thanks :)

Unfortunately I still can't release Krossbow 3.0 even with coroutines 1.6.0-RC because iOS artifacts are missing for `kotlinx-coroutines-test`, which prevents me from running CI tests for iOS - and I really don't trust those changes enough to YOLO this release.
