### ISSUE TITLE
Conditional retry

### ISSUE THREAD

**Issue by Shusek** [joffrey-bion/krossbow#172]
**Problem/use case that this feature is meant to solve/enable**
Sometimes it is useless to try to connect websocket again. In my case when i got NetworkException and code inside this exception (401) means that the session has expired.

**Describe the solution you'd like**
Add condition as parameter to retry strategy.  It should have information about the exception. Probably something like `(Throwable)->Boolean` or to be more consistent with Kotlin api (cause, attempt)->Boolean.

**Describe alternatives you've considered**
I have two separate layer with multiple suspended mutex without using library reconnecting method I plan to throw them away and simplify my code by using library reconnect mechanism.

**Comment by joffrey-bion** [comment]
Thanks a lot for the idea. I can make breaking changes in 3.0, so I'll definitely improve this!
