### ISSUE TITLE
Upgrade Dokka to version 1.7.0

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/krossbow#244]

**Comment by joffrey-bion** [comment]
Currently blocked by an incompatibility between the Kotlin stdlib in Dokka and in Gradle:
https://kotlinlang.slack.com/archives/C0F4UNJET/p1655743911527999

Should be fixed in Gradle 7.5

**Comment by vmishenev** [comment]
Current [workaround](https://github.com/Kotlin/kotlinx.coroutines/blob/2ee99e269ec37d703f44f2598b4634637d8354d6/buildSrc/build.gradle.kts#L47):
```
implementation("org.jetbrains.dokka:dokka-gradle-plugin:1.7.0") {
    exclude("org.jetbrains.kotlin", "kotlin-stdlib-jdk8")
}
```

**Comment by joffrey-bion** [comment]
Thanks @vmishenev, I'll either do this exclusion or use gradle 7.5-rc-1, not sure yet
