### ISSUE TITLE
NoClassDefFoundError: WebSocketHandshakeException

### ISSUE THREAD

**Issue by Shusek** [joffrey-bion/krossbow#246]
**Describe the bug**
When establishing websocket connection fails method `extractHandshakeStatusCode` throw exception NoClassDefFoundError  with an indication of the class WebSocketHandshakeException on android because this class is available on java JDK 11+ while android uses JDK 8.

**Reproduction and additional details**
Try to connect to websocket without proper authentication. It should throw 401 or a similar code.
Instead of proper error we got:
 `java.lang.NoClassDefFoundError: Failed resolution of: Ljava/net/http/WebSocketHandshakeException;`

Ffile affected by this error: org.hildan.krossbow.websocket.ktor.HandshakeExceptionsJvm.kt

**Context**

* Krossbow version: 2.0.2
* Krossbow artifacts used: ktor, ktor-serializer
* Kotlin version: 1.7.0
* Kotlin target(s): 1.8
android API 30

**Comment by joffrey-bion** [comment]
Thanks a lot for reporting this, I'll fix this ASAP!

This would be prevented by https://github.com/joffrey-bion/krossbow/issues/49, but unfortunately I haven't had enough incentive and time to set this up.

**Comment by joffrey-bion** [comment]
Fix deployed in 4.0.2
