### ISSUE TITLE
Okhttp interoperability with SockJs (Expected 101 but got error code 400).

### ISSUE THREAD

**Issue by TimOrtel** [joffrey-bion/krossbow#280]
I have been trying to get this library running with a Spring Server on Android.
However, I cannot manage to get Krossfit to connect with my server.

## Setup

The server code is the following ([Link to source](https://github.com/ls1intum/Artemis/blob/develop/src/main/java/de/tum/in/www1/artemis/config/websocket/WebsocketConfiguration.java#L153)): 
```java
@Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        DefaultHandshakeHandler handshakeHandler = defaultHandshakeHandler();
        // NOTE: by setting a WebSocketTransportHandler we disable http poll, http stream and other exotic workarounds and only support real websocket connections.
        // nowadays, all modern browsers support websockets and workarounds are not necessary anymore and might only lead to problems
        WebSocketTransportHandler webSocketTransportHandler = new WebSocketTransportHandler(handshakeHandler);
        registry.addEndpoint("/websocket/tracker").setAllowedOriginPatterns("*").withSockJS().setTransportHandlers(webSocketTransportHandler)
                .setInterceptors(httpSessionHandshakeInterceptor());
    }

```

The webapp connects using this code ([shortened from this source](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/core/websocket/websocket.service.ts#L147)):
```typescript
let url = `//${window.location.host}/websocket/tracker`

this.socket = new SockJS(url, undefined, { transports: 'websocket' });
        const options = {
            heartbeat: { outgoing: 10000, incoming: 10000 },
            debug: false,
            protocols: ['v12.stomp'],
        };
this.stompClient = Stomp.over(this.socket, options);

this.stompClient.debug = function () {};
        const headers = <ConnectionHeaders>{};

this.stompClient.connect(headers, ...)

```

Therefore, my attempt to connect to this service from Android is the following:

```kotlin
val client =
        StompClient(OkHttpWebSocketClient()) {
            heartBeat = HeartBeat(10.seconds, 10.seconds)
            gracefulDisconnect = false
            connectionTimeout = 20.minutes
        }

//For local testing purposes ws instead of wss
val url = "ws://host/websocket/tracker"
val session = client.connect(url)
```

## Issue

However, my connection attempts from Android always fail with http code 400 (java.net.ProtocolException: Expected HTTP 101 response but was '400 '). The connection from the webapp works just fine. 

After some debugging I figured out the code returning the code 400 is in the spring source code: [AbstractSockJsService](https://github.com/spring-projects/spring-framework/blob/main/spring-websocket/src/main/java/org/springframework/web/socket/sockjs/support/AbstractSockJsService.java#L401)

The issue is, that sockJsPath is empty when connecting from Android, but when connecting from the browser it is set to "/info".

## Question
Is my spring server configured incorrectly or is Krossbow in general not compatible with my setup?

**Comment by joffrey-bion** [comment]
Hi, thanks for opening this issue.

When using `.withSockJS()` on Spring side, you're effectively defining a SockJS server that requires a special protocol. This is why the web frontend uses `new SockJS(...)` and requires a special SockJS library to interact with the server.

So, the first thing that comes to mind is that OkHttp is a real websocket client that probably doesn't support the SockJS protocol. That being said, I think you might still be able to use OkHttp in your case. From what I understood of the Spring server, there should still be a real websocket endpoint despite the `withSockJS` configuration, but you would have to use not only a `ws://` scheme but also append `/websocket` to your route. I haven't tested that, but this is what I understand from [this SO answer](https://stackoverflow.com/a/41751897/1540818):

> A note to mention that when using only STOMP client to connect to native websocket the URL will be something like **ws://**mydomain/SockJSEndpoint**/websocket**, and when using SockJS client from the browser the URL will be like **http://**mydomain/SockJSEndpoint.

So in your case, I'm guessing the SockJS URL is `http://{host}/websocket/tracker`, so please try to change your URL to `ws://<host>/websocket/tracker/websocket` when using Krossbow and see if the problem persists.

If it still doesn't work, note that Krossbow provides a SockJS websocket implementation with the `krossbow-websocket-sockjs` dependency, which on JVM uses a Spring client under the hood which *does* support SockJS. More info here:
https://joffrey-bion.github.io/krossbow/websocket/sockjs/

**Comment by joffrey-bion** [comment]
@TimOrtel glad that this is solved for you! Did the URL `ws://{host}/websocket/tracker/websocket` solve the problem? Or did you have to switch to the `krossbow-websocket-sockjs` artifact eventually?
