### ISSUE TITLE
Support for dynamic header in OkHttpClient

### ISSUE THREAD

**Issue by okaymak** [joffrey-bion/krossbow#286]
I would like to add a dynamic header to OkHttp while using the `connect` method on `StompClient`.
Because this header is dynamic, I cannot easily use the `Interceptor` from OkHttp.

The `connect` method has a parameter for headers, but that is on stomp-level afaik.

To make it work I extended `WebSocketClient` to add a function that accepts a parameter to add as a header.
And implemented this by copying and adapting from `OkHttpWebSocketClient` and passing that to a copied and altered `StompClient`. Would be nice if this is possible from this library, probably in a more extendable manner.

**Comment by joffrey-bion** [comment]
Hi! Thanks a lot for the report. During the design, I tended to rely on the fact that you can customize the OkHttpClient passed to the websocket adapter, but maybe this is not sufficient.

I'll think of something to make it more convenient with a generic way to customize the WS connect request in the future.

In the meantime, maybe I could add a param for custom headers for the WS connect, which is a simple and easy use case.

**Comment by joffrey-bion** [comment]
I forgot to mention it here, but the first half of this was released in [5.5.0](https://github.com/joffrey-bion/krossbow/releases/tag/5.5.0):
https://github.com/joffrey-bion/krossbow/issues/360

**Comment by joffrey-bion** [comment]
Actually, this should be enough to get everything you need. With this new feature, you can connect the websocket manually using this new `headers` parameter, and then you can use the `WebSocketConnection.stomp()` extension function instead of using a `StompClient` to connect at STOMP level:

```kotlin
val webSocketClient = OkHttpWebSocketClient()

// connect at web socket level with custom headers
val wsSession = webSocketClient.connect(url, headers = mapOf("Custom-Header" to "custom-value"))


val config = StompConfig().apply {
    // here you can setup whatever config you would have setup in the StompClient { ... } block
}
// connect at STOMP level on this open web socket, using the above config
val stompSession = wsSession.stomp(config)
```

**Comment by joffrey-bion** [comment]
Closing as using the above snippet will be the way to go for custom web socket handshake.
