### ISSUE TITLE
How to subscribe to multiple channels in one connection?

### ISSUE THREAD

**Issue by Dante313** [joffrey-bion/krossbow#318]
@joffrey-bion 

Hey! Thanks for the library. I have a question for you. I have one connection to WS using STOMP. When my session is started i'm making a subscribtion to one channel. Then i'm trying to subscribe to another channel in the same connection but the second connection doesn't appear. Can you help me with that? I need to make two subscriptions somehow. Looks like creating two connections for this purpose is not great idea :/

Example:

```
val session = stompClient.connect(BASE_WS_URL).withJsonConversions()

        session.use {
            val sessionWithJson = session as? StompSessionWithKxSerialization ?: return

            sessionWithJson.subscribe(
                "first/destintation,
                FirstNetworkModel.serializer()
            ).collect { /** Working as expected */ }

            sessionWithJson.subscribe(
                "second/destination,
                SecondNetworkModel.serializer()
            ).collect { /** Doesn't work */ }
        }
```

**Comment by Dante313** [comment]
@joffrey-bion oh got it. Thanks for such a quick respond. About casting: nevermind, i'm just using `StompConnection` in my code, so i need to cast it to be able to use method with serializer :)

**Comment by joffrey-bion** [comment]
If you're doing this because you find the name a bit long, you could also define some typealias somewhere like:

```kotlin
typealias MyStompSession = StompSessionWithKxSerialization
```

**Comment by Dante313** [comment]
@joffrey-bion thank you so much :) by the way your first respond is working great so this issue can be closed
