### ISSUE TITLE
Define a specific `SessionDisconnectedException` to represent STOMP frames completion

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/krossbow#379]
### Problem / use case

When sending frames and waiting for receipts, the session might be disconnected in the meantime. This currently throws an `IllegalStateException`, which is not very user friendly: we don't want to explicitly catch this exception, but we want to be able to handle such errors when making `send()` calls.

### Feature (solution)

If the user of the `StompSession` decided to disconnect while another coroutine was waiting for a receipt, we could instead throw a specific `SessionDisconnectedException` instead of `IllegalStateException`.

### Current alternatives

Catch the `IllegalStateException` and analyze the message... which is quite brittle and not very maintainable.

**Comment by mahmed1987** [comment]
@joffrey-bion  how should i catch this exception ?

Currently my application just crashes with this exception

**Comment by joffrey-bion** [comment]
This exception should occur at the `send` call site if my memory serves me well. So you should be able to catch it there.

Note, however, that this means the server didn't confirm the reception of the message, and you already disconnected the session.
You might want to avoid this in the first place. Could you please describe why you need this?

**Comment by mahmed1987** [comment]
hmm interesting @joffrey-bion  I dont know how come it has suddenly started to happen . This is happening on a new disconnect call that some team member of mine has placed . 

Could it be that double disconnection is causing this situation to occur ? . 

Right now it doesn't occur everytime , but I saw it twice. I would revert back to you after I have a proven test scenario ?

Thanks

**Comment by joffrey-bion** [comment]
Ah, it's definitely possible that `disconnect()` causes this too if another disconnection happened at the same time.

This was not the intended behavior. I will look into this.

In the meantime, as a workaround I think you could add a `try`/`catch` around the `disconnect` calls.
