### ISSUE TITLE
Reconnecting after an error requires a delay

### ISSUE THREAD

**Issue by lemkoleg** [joffrey-bion/krossbow#571]
### What happened?

I'm not sure if this is a bug. But if WebSocket failed to connect (resource unavailable), then the next attempt will be very short-lived. That is, the first attempt to connect has a 10 second timeout, then the next 30-40 milliseconds. And this will continue for about 10 seconds. Then again the attempt will have a 10 second timeout. Could it be that the same outgoing connection port is used? It is possible that this is because after a failed connection attempt, the port remains busy for some time. Maybe I'm wrong

### Krossbow version

7.3.0

### Krossbow modules

krossbow-websocket-ktor

### Kotlin version

1.9.2 / 2.0.0

### Kotlin target platforms

Android

**Comment by lemkoleg** [comment]
I didn't go too deep into the problem, I decided to make a cycle, with a delay, for a second attempt. The only way I could reproduce this phenomenon was when I tried to connect a virtual device to a local machine. And even then - it is unstable.

**Comment by joffrey-bion** [comment]
Ah I didn't realize you were manually implementing the retry, and not using the `ReconnectingWebSocketClient` nor the built-in Ktor retry mechanism. Ok then I'll just mark this issue as resolved, because this is a matter of how you implement the retry yourself.
