### ISSUE TITLE
Feature - WebSocket Reconnecting Strategy

### ISSUE THREAD

**Issue by lost-illusi0n** [joffrey-bion/krossbow#94]
**Please describe the problem/use case that this feature is meant to solve/enable**
Currently if a websocket is abruptly closed server side, e.g., it crashed, krossbow will close the session silently. There doesn't seem to be any kind of listener for this, as the onError methods within WebSocketChannel, simply close the Channel of incoming frames, without any explicit event for the user.

**Describe the solution you'd like**
There could be a few solutions. One being that krossbow allows for some reconnect strategy (could have default implementations, but also allow for custom user implementations), and takes it into account whenever onError is called. This configuration should probably be passed into the underlying WebSocketClient of StompClient, e.g.
```kotlin
val client = StompClient(
    webSocketClient = Jdk11WebSocketClient(reconnectStrategy = ConstantReconnectStrategy(delayInSeconds = 5))
)
```
This is because, I do not think that the reconnect logic should be handled by the Stomp implementation, but more so the underlying websocket session, but how that would be implemented is still up for debate, this is just one possible way.

The ReconnectStrategy could simply be an interface which looks something like this
```kotlin
fun interface ReconnectStrategy {
    fun calculateReconnectDelay(attempt: Int) : Int
}
```

There could also be a `maxAttempt` value that is set somewhere, which will finally close the session if it wasn't able to reconnect within the allowed maximum attempts using the specified `ReconnectStrategy`. This could also be implemented within the `ReconnectStrategy`, e.g. if the value returned by `ReconnectStrategy#calculateReconnectDelay` is -1, then that could be a signal for krossbow to stop trying to reconnect. There's a bunch of room for discussion but personally I feel as if the ReconnectStrategy is the best way reconnecting could be accomplished within krossbow, as it allows for a bunch of wiggle room for a end user to customize what they want to do when there is a websocket level error.

Note: I only skimmed through the methods of the JVM jdk11 implementation, so I'm not sure how viable implementing reconnect logic within other implementations would be, however I couldn't imagine it being drastically different.

**Describe alternatives you've considered**
The lack of transparency to the user, when the connection is lost, means the only way (I can think of), to figure out when a websocket is closed and do something when that does happen, is to have a terminal flow on a subscription (not sure if this is the right terminology), and since the flow originates from the frame channel, whenever the channel is closed, all terminating flows will throw the WebSocketException. Though having to require to call a subscribe method, turn it into a terminating flow, catch the exception, and then do your logic, to handle reconnect logic isn't exactly pretty.

The following is one way you can make a *hacky* listener for web socket level errors.
```kotlin
val session = client.connect(...)
try {
    session.subscribe(...).collect { ... }
catch(e: WebSocketException) {
     // logic here
}
```

**Context**
Kotlin version: 1.4.2
Kotlin target: JVM

As you may imagine by the topic of this feature, and the entire feature itself, I'm trying to get a reconnecting websocket. This doesn't seem like a bizarre use case, since, for example, if I briefly restart by websocket server, e.g. for an update, I'd like for the client to keep on reconnecting until it comes back up. Though my initial roadblock was the lack of any obvious way of telling if and when the websocket is closed, it became clear to me after looking through krossbow that there is no reconnect logic within krossbow to my knowledge. Thanks for reading this :-)

**Comment by joffrey-bion** [comment]
Thanks a lot for opening this issue. So far, there is almost no configuration for the websocket client itself because I relied on the fact that the user always has control over the actual web socket implementation (you can pass your own instance of the JDK's websocket, or Spring web socket etc.).

That being said, it is indeed annoying for users that are interested in the multiplatform aspect of the lib (they don't want to care about each individual implementation).

I was considering migrating to Kotlin's `Flow` for the API of the web socket client for some time now, and there might be something we could do with this in a more composable way. I will definitely think about it.

**Comment by lost-illusi0n** [comment]
Well, while you did say you never designed the WebSocketClient to be configurable, that gave me the idea to just implement my own WebSocketClient which now has a sort of "watchdog", polling to see if the websocket session (switched over to ktor's websocket implementation, since that was the easiest) incoming channel ever closed. If it does detect the closed channel, it'll attempt to create a new Ktor `DefaultClientWebSocketSession` and replace the session within the adapter. For my usecase it seems to be working great so far, though I'll stilll have to implement a way to persist subscriptions throughout reconnects. Though it's definitely better than nothing.

That aside, now that I've seen how most of how the websockets are implemented, there doesn't seem to be any "event", for when a websocket is closed iirc, or at least nothing that is standard for all websocket implementations. So I do still think the best way would be to leverage the incomingFrames channel within the `WebSocketSession`, or some other channel/flow originating from that. However, what is the best way to keep subscriptions between reconnect is something I'm not so sure yet.

Thanks for thanking the time to read and consider this, and indirectly giving me an idea how to implement it for myself as well though. 👍

**Comment by joffrey-bion** [comment]
Great that you could find an alternative.

I will keep this open, as I believe this kind of adapter would be useful for many people, and is worth providing within the library.

I will also try to make it easier to deal with websocket closure/errors from the user's perspective, without any need to implement your own adapter.
